pasta_in = ("tomato","garlic","garlic","olive_oil")
biryani_in = ("spices","rice","chicken","garlic")
print("\npasta_in",pasta_in)
print("total ingradients in pasta:",len(pasta_in)) 
pasta_in.add("leaves")
pasta_in.discard("olive_oil")
print("\nupdated pasta ingradeints:",pasta_in)
all_ingradients = pasta_in.union(biryani_in)
common = pasta_in.intersection(biryani_in)
only_pasta = pasta_in.difference(biryani_in)
unique = pasta_in.symmetric_difference(biryani_in)
print("\nall_ingradients(union):",all_ingradients)
print("\ncommon(intersection):",common)
print("\nonly_pasta(difference):",only_pasta)
print("\nunique(symmetric.diff):",unique)